sudo: required
language: generic
services:
  -docker

before_install:
  - docker build -t taariasdckr95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true taariasdckr95/docker-react npm run test
