FROM node:16-alpine

WORKDIR '/app'

#copy contents of package.json to WORKDIR
COPY package.json .

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install --force

#COPY everything else
COPY . .

RUN chown -R node:node /app/node_modules

User node

CMD ["npm", "run", "start"]